import { describe, it } from "node:test";
import assert from "node:assert/strict";
import { existsSync } from "node:fs";
import { mkdir, rm } from "node:fs/promises";
import { join } from "node:path";
import { parsePngDiffArgs, runPngDiff } from "./png-diff.ts";
import { encodePng } from "./png-utils.ts";

const TMP = join(import.meta.dirname!, "..", "test-results", "png-diff-test");

function createPalettePng(
  width: number,
  height: number,
  colors: Array<[number, number, number]>,
): { width: number; height: number; data: Uint8Array } {
  const data = new Uint8Array(width * height * 4);
  const cols = 3;
  const rows = Math.ceil(colors.length / cols);
  const cellWidth = Math.floor(width / cols);
  const cellHeight = Math.floor(height / rows);

  for (let i = 0; i < colors.length; i++) {
    const [r, g, b] = colors[i];
    const col = i % cols;
    const row = Math.floor(i / cols);
    const startX = col * cellWidth;
    const startY = row * cellHeight;
    const endX = col === cols - 1 ? width : startX + cellWidth;
    const endY = row === rows - 1 ? height : startY + cellHeight;

    for (let y = startY; y < endY; y++) {
      for (let x = startX; x < endX; x++) {
        const offset = (y * width + x) * 4;
        data[offset] = r;
        data[offset + 1] = g;
        data[offset + 2] = b;
        data[offset + 3] = 255;
      }
    }
  }

  return { width, height, data };
}

describe("png-diff", () => {
  it("parses CLI flags for direct PNG comparison", () => {
    const options = parsePngDiffArgs([
      "before.png",
      "after.png",
      "--output-dir",
      "tmp/out",
      "--threshold",
      "0.2",
      "--json",
      "--no-heatmap",
    ]);

    assert.equal(options.baselinePath, "before.png");
    assert.equal(options.currentPath, "after.png");
    assert.equal(options.outputDir, "tmp/out");
    assert.equal(options.threshold, 0.2);
    assert.equal(options.json, true);
    assert.equal(options.skipHeatmap, true);
  });

  it("compares two PNG files without Playwright", async () => {
    const baselinePath = join(TMP, "baseline.png");
    const currentPath = join(TMP, "current.png");

    const baselineColors: Array<[number, number, number]> = [
      [40, 80, 140],
      [60, 120, 160],
      [80, 160, 120],
      [120, 160, 80],
      [140, 120, 60],
      [100, 100, 160],
      [60, 140, 120],
      [120, 120, 120],
      [80, 80, 80],
    ];
    const currentColors = [...baselineColors];
    currentColors[4] = [90, 150, 210];

    await rm(TMP, { recursive: true, force: true });
    await mkdir(TMP, { recursive: true });

    try {
      await encodePng(baselinePath, createPalettePng(120, 120, baselineColors));
      await encodePng(currentPath, createPalettePng(120, 120, currentColors));

      const result = await runPngDiff({
        baselinePath,
        currentPath,
        outputDir: TMP,
        threshold: 0.1,
        skipHeatmap: false,
        json: false,
      });

      assert.ok(result.diff.diffPixels > 0);
      assert.equal(result.diff.snapshot.baselinePath, baselinePath);
      assert.equal(result.diff.snapshot.screenshotPath, currentPath);
      assert.ok(result.semantic.summary.length > 0);
      assert.ok(result.diff.heatmapPath, "heatmap should be generated by default");
      assert.ok(existsSync(result.diff.heatmapPath!), "heatmap file should exist");
    } finally {
      await rm(TMP, { recursive: true, force: true });
    }
  });
});
